implement `spin -vvvvv`
This provides an alternative to `RUST_LOG=spin=trace`.

Most non-rust users are familiar with the `-vvvvv` pattern for
command-line interfaces. This provides an easy way to change between the
five different log levels:

- 0: "off"
- 1: "error"
- 2: "warn"
- 3: "info"
- 4: "debug"
- 5: "trace"

Remembering the number of occurrences of a flag is easier to remember
than the string values for each log level, as each language/framework
can use different terminology or letter casing for different log levels.

```
$ ../../target/debug/spin -vvvvv bindle push --bindle-server http://localhost:8080/v1
2022-06-28T19:27:14.367304Z TRACE new: bindle::standalone: Computed invoice file path invoice_path=/tmp/.tmp55Qe0T/64b479265e1f51ccc669de307a054e2c3fd4756eb0eae6ebfbe1bfde7ca37eeb/invoice.toml
2022-06-28T19:27:14.367367Z TRACE new: bindle::standalone: Listing parcels in parcels directory parcels_dir=/tmp/.tmp55Qe0T/64b479265e1f51ccc669de307a054e2c3fd4756eb0eae6ebfbe1bfde7ca37eeb/parcels
2022-06-28T19:27:14.367759Z  INFO bindle::client: Provided base URL missing trailing slash, adding...
2022-06-28T19:27:14.391917Z TRACE get_yanked_invoice{invoice_id=spin-hello-world/1.0.0}: bindle::client: req=RequestBuilder { method: GET, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(8080), path: "/v1/_i/spin-hello-world/1.0.0", query: Some("yanked=true"), fragment: None }, headers: {} }
2022-06-28T19:27:14.392072Z TRACE get_yanked_invoice{invoice_id=spin-hello-world/1.0.0}: hyper::client::pool: checkout waiting for idle connection: ("http", localhost:8080)
2022-06-28T19:27:14.392146Z DEBUG get_yanked_invoice{invoice_id=spin-hello-world/1.0.0}: reqwest::connect: starting new connection: http://localhost:8080/
2022-06-28T19:27:14.392229Z TRACE get_yanked_invoice{invoice_id=spin-hello-world/1.0.0}: hyper::client::connect::http: Http::connect; scheme=Some("http"), host=Some("localhost"), port=Some(Port(8080))
2022-06-28T19:27:14.392337Z DEBUG hyper::client::connect::dns: resolving host="localhost"
2022-06-28T19:27:14.392592Z DEBUG get_yanked_invoice{invoice_id=spin-hello-world/1.0.0}: hyper::client::connect::http: connecting to 127.0.0.1:8080
2022-06-28T19:27:14.392712Z TRACE get_yanked_invoice{invoice_id=spin-hello-world/1.0.0}: mio::poll: registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
2022-06-28T19:27:14.392819Z TRACE get_yanked_invoice{invoice_id=spin-hello-world/1.0.0}: mio::poll: deregistering event source from poller
2022-06-28T19:27:14.392887Z TRACE get_yanked_invoice{invoice_id=spin-hello-world/1.0.0}: hyper::client::connect::http: connect error for 127.0.0.1:8080: ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })
2022-06-28T19:27:14.392959Z TRACE get_yanked_invoice{invoice_id=spin-hello-world/1.0.0}: hyper::client::pool: checkout dropped for ("http", localhost:8080)
2022-06-28T19:27:14.393093Z TRACE push: bindle::standalone: Loading invoice file from disk path=/tmp/.tmp55Qe0T/64b479265e1f51ccc669de307a054e2c3fd4756eb0eae6ebfbe1bfde7ca37eeb/invoice.toml
2022-06-28T19:27:14.393745Z DEBUG push: bindle::standalone: Attempting to create invoice invoice_id=spin-hello-world/1.0.0
2022-06-28T19:27:14.393931Z TRACE push:create_invoice{id=spin-hello-world/1.0.0}: bindle::client: req=RequestBuilder { method: POST, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(8080), path: "/v1/_i", query: None, fragment: None }, headers: {"content-type": "application/toml"} }
2022-06-28T19:27:14.394018Z TRACE push:create_invoice{id=spin-hello-world/1.0.0}: hyper::client::pool: checkout waiting for idle connection: ("http", localhost:8080)
2022-06-28T19:27:14.394076Z DEBUG push:create_invoice{id=spin-hello-world/1.0.0}: reqwest::connect: starting new connection: http://localhost:8080/
2022-06-28T19:27:14.394132Z TRACE push:create_invoice{id=spin-hello-world/1.0.0}: hyper::client::connect::http: Http::connect; scheme=Some("http"), host=Some("localhost"), port=Some(Port(8080))
2022-06-28T19:27:14.394192Z DEBUG hyper::client::connect::dns: resolving host="localhost"
2022-06-28T19:27:14.394286Z DEBUG push:create_invoice{id=spin-hello-world/1.0.0}: hyper::client::connect::http: connecting to 127.0.0.1:8080
2022-06-28T19:27:14.394355Z TRACE push:create_invoice{id=spin-hello-world/1.0.0}: mio::poll: registering event source with poller: token=Token(16777217), interests=READABLE | WRITABLE
2022-06-28T19:27:14.394433Z TRACE push:create_invoice{id=spin-hello-world/1.0.0}: mio::poll: deregistering event source from poller
2022-06-28T19:27:14.394479Z TRACE push:create_invoice{id=spin-hello-world/1.0.0}: hyper::client::connect::http: connect error for 127.0.0.1:8080: ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })
2022-06-28T19:27:14.394514Z TRACE push:create_invoice{id=spin-hello-world/1.0.0}: hyper::client::pool: checkout dropped for ("http", localhost:8080)
Error: Failed to push bindle to server

Caused by:
    0: Failed to push bindle from '/tmp/.tmp55Qe0T' to server at 'http://localhost:8080/v1'
    1: Error creating request
    2: error sending request for url (http://localhost:8080/v1/_i): error trying to connect: tcp connect error: Connection refused (os error 111)
    3: error trying to connect: tcp connect error: Connection refused (os error 111)
    4: tcp connect error: Connection refused (os error 111)
    5: Connection refused (os error 111
```

Signed-off-by: Matthew Fisher <matt.fisher@fermyon.com>