Require raw app manifest to be valid
Previously, raw app manifest was validated explicitly during the app
publishing/load. Running validations automatically in the loader looks
like a safer approach.

From the user's perspective, from now on, the invalid manifest will
make the build to fail (as well as `spin up`, `spin bindle prepare/push`,
`spin deploy`):

$ spin build
Error: One or more allowed_http_hosts entries was invalid:
ftp://some-random-api.ml isn't a valid host or host:port string
example.com/wib/wob contains a path, should be host and optional port only

Signed-off-by: Konstantin Shabanov <mail@etehtsea.me>