feat: Include manifest file name into error output
Before:

$ ../../target/debug/spin build
Error: expected a comma, found an identifier at line 9 column 28

After:

$ ../../target/debug/spin build
Error: Cannot read manifest file from "spin.toml"

Caused by:
    expected a comma, found an identifier at line 9 column 28

Refs: #769
Signed-off-by: Konstantin Shabanov <mail@etehtsea.me>