fix(spin-redis-engine): Fix error during startup
Fixes the following error:

$ spin build up --follow-all
<..>
Successfully ran the build command for the Spin components.
Error: Failed to configure Redis trigger

Caused by:
    metadata error: missing required "redis_address"
Error: exit status: 1

Refs: #763.
Closes #799.

Signed-off-by: Konstantin Shabanov <mail@etehtsea.me>