feat(spin-redis-engine): Improve connection error msg
Example:

2022-10-03T09:04:25.628294Z ERROR spin_trigger::cli: Trigger executor failed
Error: Redis trigger failed to connect to redis://localhost:6379

Caused by:
    Connection refused (os error 111)
Error: exit status: 1

Closes #704.

Signed-off-by: Konstantin Shabanov <mail@etehtsea.me>