fix(deploy): Prevent swallowing the error
When I tried to deploy example before building it, it failed with
quite confusing error.

An explicit recommendation to run `spin build` could be even better
solution but this workaround should be good enough before more
long-term solution is introduced.

Before:

$ ../../target/debug/spin deploy
Error: Failed to expand 'spin.toml' to a bindle

Learn more at https://developer.fermyon.com/cloud/faq

After:

$ ../../target/debug/spin deploy
Error: Failed to expand 'spin.toml' to a bindle

Caused by:
    0: Failed to convert components to Bindle format
    1: Failed to get parcel id for 'examples/http-rust-outbound-http/target/wasm32-wasi/release/http_rust_outbound_http.wasm'
    2: No such file or directory (os error 2)

Learn more at https://developer.fermyon.com/cloud/faq

Signed-off-by: Konstantin Shabanov <mail@etehtsea.me>